name: ATLAS Workflow

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov
      - name: Install project dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Clear pytest cache
        run: |
          pytest --cache-clear
      - name: Run unittests
        run: |
          pytest --cov=src -s tests